  # 数据库连接地址
spring.datasource.url=jdbc:mysql://localhost:3306/jeesite?useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf8
  # 数据库用户名&密码：
spring.datasource.username=root
spring.datasource.password=123456
  # mybatis配置
mybatis.mapper-locations=classpath:/mapper/*.xml
logging.level.com.zj=debug